CXX = g++
CXXFLAGS = -std=c++17 -Iinclude -fPIC
LDFLAGS = -ldl

SRC_DIR = src
BUILD_DIR = build
INCLUDE_DIR = include
TEST_DIR = tests

all: $(BUILD_DIR) $(BUILD_DIR)/libfn1.so $(BUILD_DIR)/libfn2.so $(BUILD_DIR)/main_compile $(BUILD_DIR)/main_runtime $(BUILD_DIR)/test_fn1 $(BUILD_DIR)/test_fn2

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/libfn1.so: $(SRC_DIR)/fn1.cpp $(INCLUDE_DIR)/fn1.hpp
	$(CXX) $(CXXFLAGS) -shared $< -o $@

$(BUILD_DIR)/libfn2.so: $(SRC_DIR)/fn2.cpp $(INCLUDE_DIR)/fn2.hpp
	$(CXX) $(CXXFLAGS) -shared $< -o $@

$(BUILD_DIR)/main_compile: $(SRC_DIR)/main_compile.cpp
	$(CXX) $(CXXFLAGS) $(SRC_DIR)/main_compile.cpp -o $@ $(BUILD_DIR)/libfn1.so

$(BUILD_DIR)/main_runtime: $(SRC_DIR)/main_runtime.cpp
	$(CXX) $(CXXFLAGS) $(SRC_DIR)/main_runtime.cpp -o $@ $(LDFLAGS)


$(BUILD_DIR)/test_fn1: $(TEST_DIR)/test_fn1.cpp $(INCLUDE_DIR)/fn1.hpp
	$(CXX) $(CXXFLAGS) $< -o $@ $(BUILD_DIR)/libfn1.so -lgtest -lgtest_main

$(BUILD_DIR)/test_fn2: $(TEST_DIR)/test_fn2.cpp $(INCLUDE_DIR)/fn2.hpp
	$(CXX) $(CXXFLAGS) $< -o $@ $(BUILD_DIR)/libfn2.so -lgtest -lgtest_main

clean:
	rm -rf $(BUILD_DIR)